<a href="https://colab.research.google.com/github/8WHOVIAN8/DAstudy/blob/%EC%B5%9C%EC%9C%A0%EC%84%A0/Ch4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np #넘파이를 사용하기 위해서 import

In [ ]:
#실습코드4-1
arr = np.array([1,2,3,4,5]) #1차원 list로 배열 생성
print(arr)

[1 2 3 4 5]


In [ ]:
#실습코드4-2
arr = np.array([[1,2,3],[4,5,6]]) #2차원 list로 배열 생성
print(arr)

[[1 2 3]
 [4 5 6]]


In [ ]:
#실습코드4-3
arr = np.array([[[1,2,3],[4,5,6],[7,8,9]], #3차원 list로 배열 생성, []의 개수가 차원 명시
                [[1,2,3,],[4,5,6],[7,8,9]],
                [[1,2,3],[4,5,6],[7,8,9]]])
print(arr)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [ ]:
a = np.zeros(5)
b = np.zeros((3,3))
c = np.ones(5)
d = np.ones((2,2)) #인덱스 2개로 2차원 배열
e = np.full((3,3),4) #3*3 matrix에 어떤 값 넣을지
f = np.eye(3) #주대각선의 원소가 1
print(a)
print(b)
print(c)
print(d)
print(e)
print(f)

[0. 0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[1. 1. 1. 1. 1.]
[[1. 1.]
 [1. 1.]]
[[4 4 4]
 [4 4 4]
 [4 4 4]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
#실습코드4-4
a = np.arange(1,15)
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [ ]:
#실습코드4-5
a = np.linspace(0,10,5) #범위 내에서 균등 간격의 배열 생성
print(a)

[ 0.   2.5  5.   7.5 10. ]


In [ ]:
#실습코드4-6
a = np.logspace(np.log10(10), np.log10(100), 5) #범위 내에서 로그 스케일로 배열 생성
print(a)

b = np.logspace(1,2,5)
print(b)

[ 10.          17.7827941   31.6227766   56.23413252 100.        ]
[ 10.          17.7827941   31.6227766   56.23413252 100.        ]


In [ ]:
#실습코드4-7
a = np.random.random() #랜덤으로 생성
print(a)

b = np.random.random((4,4)) #4*4 배열로 랜덤 수 생성
print(b)

0.255035867017924
[[0.64495787 0.24626898 0.14556039 0.03519269]
 [0.16277639 0.04873044 0.42745247 0.42184979]
 [0.40437526 0.5551482  0.87748491 0.78475693]
 [0.01471817 0.27339599 0.60505602 0.55538819]]


In [ ]:
#실습코드4-8
a = np.random.randint(1,10)
print(a)

b = np.random.randint(1,10,(4,4))
print(b)

2
[[2 9 9 9]
 [1 2 9 1]
 [2 8 8 8]
 [1 2 4 8]]


In [ ]:
#실습코드4-9
a = np.random.rand(3,3)
print(a)

[[0.96904911 0.09135736 0.96070479]
 [0.6565424  0.70866451 0.05513633]
 [0.15129051 0.34178667 0.51806279]]


In [ ]:
#실습코드4-10
a = np.random.randn(3,3)
print(a)

[[-0.9175176   2.14108291 -0.84943232]
 [ 2.09702767 -0.17542317  0.52581438]
 [ 0.32587056 -0.05351096  0.59047477]]


In [ ]:
#실습코드4-11
arr = np.arange(1,6)
print(arr)
print('ndim:', arr.ndim) #배열 차원 수
print('shape:', arr.shape)
print('dtype:', arr.dtype)
print('size', arr.size)
print('itemsize', arr.itemsize)
print('nbytes', arr.nbytes)

[1 2 3 4 5]
ndim: 1
shape: (5,)
dtype: int64
size 5
itemsize 8
nbytes 40


In [ ]:
#실습코드4-12
a1 = np.arange(9)
print(a1)
print(a1[0])
print(a1[-1])
print(a1[-3])
a1[0]=10
print(a1)

[0 1 2 3 4 5 6 7 8]
0
8
6
[10  1  2  3  4  5  6  7  8]


In [ ]:
#실습코드4-13
a2 = np.arange(9).reshape((3,3))
print(a2)
print(a2[0,1])
print(a2[1,2])
a2[0,0]=10
print(a2)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
1
5
[[10  1  2]
 [ 3  4  5]
 [ 6  7  8]]


In [ ]:
#실습코드4-14
a1 = np.arange(6)
print(a1)
print(a1[0:3])
print(a1[1:])
print(a1[-2:])
print(a1[:-3])
print(a1[::2])
print(a1[::-1])


[0 1 2 3 4 5]
[0 1 2]
[1 2 3 4 5]
[4 5]
[0 1 2]
[0 2 4]
[5 4 3 2 1 0]


In [ ]:
#실습코드4-15
a2 = np.arange(1,25).reshape((4,6))
print(a2[1])
print(a2[1:3,1:5])
print(a2[2,:])
print(a2[:3,:3])
print(a2[2:,::-1])
print(a2[::-1,::-1])

[ 7  8  9 10 11 12]
[[ 8  9 10 11]
 [14 15 16 17]]
[13 14 15 16 17 18]
[[ 1  2  3]
 [ 7  8  9]
 [13 14 15]]
[[18 17 16 15 14 13]
 [24 23 22 21 20 19]]
[[24 23 22 21 20 19]
 [18 17 16 15 14 13]
 [12 11 10  9  8  7]
 [ 6  5  4  3  2  1]]


In [ ]:
#실습코드4-16
a = np.arange(1,6)
print(a)
b = [True,False,False,True,False]
print(a[b])

[1 2 3 4 5]
[1 4]


In [ ]:
a = np.arange(11)
print(a[a<5])
five_up = (a>=5)
five_up
print(a[five_up])
divide_by_2 = a[a%2==0]
print(divide_by_2)

[0 1 2 3 4]
[ 5  6  7  8  9 10]
[ 0  2  4  6  8 10]


In [ ]:
#실습코드4-18
c = a[(a>5) & (a<11)]
print(c)
d = a[(a>9) | (a<5)]
print(d)
e = a[~(a%3==0)]
print(e)

[ 6  7  8  9 10]
[ 0  1  2  3  4 10]
[ 1  2  4  5  7  8 10]


In [ ]:
#실습코드4-19
a = np.arange(1,11)
b = np.arange(1,11)
print(a+b)
print(np.add(a,b))
print(a-b)
print(np.subtract(a,b))
print(a*b)
print(np.multiply(a,b))
print(a/b)
print(np.divide(a,b))

[ 2  4  6  8 10 12 14 16 18 20]
[ 2  4  6  8 10 12 14 16 18 20]
[0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0]
[  1   4   9  16  25  36  49  64  81 100]
[  1   4   9  16  25  36  49  64  81 100]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [ ]:
#실습코드4-20
a = np.arange(1,11)
print(np.exp(a))
print(np.sqrt(a))
print(np.sin(a))
print(np.cos(a))
print(np.tan(a))
print(np.log(a))

[2.71828183e+00 7.38905610e+00 2.00855369e+01 5.45981500e+01
 1.48413159e+02 4.03428793e+02 1.09663316e+03 2.98095799e+03
 8.10308393e+03 2.20264658e+04]
[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712 3.         3.16227766]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155
  0.6569866   0.98935825  0.41211849 -0.54402111]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219  0.96017029
  0.75390225 -0.14550003 -0.91113026 -0.83907153]
[ 1.55740772 -2.18503986 -0.14254654  1.15782128 -3.38051501 -0.29100619
  0.87144798 -6.79971146 -0.45231566  0.64836083]
[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458 2.30258509]


In [ ]:
#실습코드4-21
a = np.arange(1,10).reshape(3,3)
print(a.sum())
print(np.sum(a))
print(a)
b = a.sum(axis=0)
print(b)
c = a.sum(axis=1)
print(c)

45
45
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[12 15 18]
[ 6 15 24]


In [ ]:
#실습코드4-22
a = np.arange(1,10).reshape(3,3)
print(a)
print(a.max(),np.max(a))
print(a.max(axis=0), np.max(a,axis=0))
print(a.max(axis=1), np.max(a,axis=1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
9 9
[7 8 9] [7 8 9]
[3 6 9] [3 6 9]


In [ ]:
#실습코드4-23
a = np.arange(1,10).reshape(3,3)
print(a)
print(a.min(), np.min(a))
print(a.min(axis=0), np.min(a,axis=0))
print(a.min(axis=1), np.min(a,axis=1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
1 1
[1 2 3] [1 2 3]
[1 4 7] [1 4 7]


In [ ]:
#실습코드4-24
a = np.arange(1,10).reshape(3,3)
print(a)
print(a.mean(),np.mean(a))
print(a.mean(axis=0),np.mean(a,axis=0))
print(a.mean(axis=1),np.mean(a,axis=1))
print(np.median(a))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
5.0 5.0
[4. 5. 6.] [4. 5. 6.]
[2. 5. 8.] [2. 5. 8.]
5.0


In [ ]:
#실습코드4-25
a = np.arange(1,10).reshape(3,3)
print(a)
print(a.std(), np.std(a))
print(a.std(axis=0), np.std(a,axis=0))
print(a.std(axis=1), np.std(a,axis=1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
2.581988897471611 2.581988897471611
[2.44948974 2.44948974 2.44948974] [2.44948974 2.44948974 2.44948974]
[0.81649658 0.81649658 0.81649658] [0.81649658 0.81649658 0.81649658]


In [ ]:
#실습코드4-26
x = np.array([1,2,3,4,5])
y = np.array([1,1,1,1,1])
print(x+y)
y=1 #broadcasting이란 shape이 맞지 않을 때, 확장을 시켜서 맞추는 것
print(x+y)

[2 3 4 5 6]
[2 3 4 5 6]


In [ ]:
#실습코드4-27
a = np.arange(1,25).reshape(4,6)
print(a+100)
new_arr = np.full_like(a,100)
print(new_arr)
print(a+new_arr)

[[101 102 103 104 105 106]
 [107 108 109 110 111 112]
 [113 114 115 116 117 118]
 [119 120 121 122 123 124]]
[[100 100 100 100 100 100]
 [100 100 100 100 100 100]
 [100 100 100 100 100 100]
 [100 100 100 100 100 100]]
[[101 102 103 104 105 106]
 [107 108 109 110 111 112]
 [113 114 115 116 117 118]
 [119 120 121 122 123 124]]


In [ ]:
a = np.arange(5).reshape((1,5))
print(a)
b = np.arange(5).reshape((5,1))
print(b)
print(a+b)

[[0 1 2 3 4]]
[[0]
 [1]
 [2]
 [3]
 [4]]
[[0 1 2 3 4]
 [1 2 3 4 5]
 [2 3 4 5 6]
 [3 4 5 6 7]
 [4 5 6 7 8]]


In [ ]:
import time
a = np.arange(10000000)
result = 0
s = time.time()
for v in a:
  result += v
e = time.time()
print(result, e-s)
s = time.time()
result = np.sum(a)
e = time.time()
print(result,e-s)

49999995000000 2.8093924522399902
49999995000000 0.00928354263305664


In [ ]:
a = np.random.randint(1,10,(3,3))
print(a)
print(a.T)

[[6 1 7]
 [7 1 4]
 [1 3 5]]
[[6 7 1]
 [1 1 3]
 [7 4 5]]


In [ ]:
a = np.array([[1,2,3],[4,5,6]])
print(a)
a.ravel()
b = a.ravel()
b[0] = 10
print(b)
print(a)

[[1 2 3]
 [4 5 6]]
[10  2  3  4  5  6]
[[10  2  3]
 [ 4  5  6]]


In [ ]:
x = np.arange(20)
y = x.reshape(4,5)
print(y)
x[0] = 10
print(x)
print(y)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[10  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[[10  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [ ]:
list_data = [1,2,3,4,5,6]
#list_data.reshape(3,2)
data = np.array(list_data)
type(data)
print(data.reshape(3,2))
print(list_data)

[[1 2]
 [3 4]
 [5 6]]
[1, 2, 3, 4, 5, 6]


In [ ]:
x = np.arange(20)
y = np.resize(x,(5,4))
y
#새 배열에 요소 수가 많으면 원래 가지고 있는 배열의 데이터 반복
#새 배열에 요소 수가 적으면 필요한 요소 수를 행 순서대로 가져온

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [ ]:
a=np.arange(3)
b=np.append(a,3)
print(b)

[0 1 2 3]


In [ ]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[7,8,9]]) #축을 지정하지 않았기 때문에 1차원 배열로 바꿔서 출력된다
c=np.append(a,b)
print(c)

[1 2 3 4 5 6 7 8 9]


In [ ]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[7,8,9]])
c=np.append(a,b,axis=0) #첫 번째 축을 기준으로 추가해서 2차원 배열을 만들었다
print(c)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
a=np.array([1,2,3])
b=np.insert(a,1,5)
print(a)
print(b)

c=np.array([[1,1],[2,2],[3,3]])
d=np.insert(a,1,5)
print(c)
print(d)

[1 2 3]
[1 5 2 3]
[[1 1]
 [2 2]
 [3 3]]
[1 5 2 3]


In [ ]:
a=np.arange(12).reshape(3,4)
print(a)
print(np.delete(a,1,axis=0))
print(np.delete(a,1,axis=1))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3]
 [ 8  9 10 11]]
[[ 0  2  3]
 [ 4  6  7]
 [ 8 10 11]]


In [ ]:
#연습문제1
arr=np.arange(1,11)
print(arr)
print('ndim:',arr.ndim)
print(arr.shape)
print(arr.dtype)
print('size:',arr.size)

[ 1  2  3  4  5  6  7  8  9 10]
ndim: 1
(10,)
int64
size: 10


In [ ]:
#연습문제2-1
a=np.arange(51)
c=a[(a>9) & (a<50)]


[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [ ]:
#연습문제2-2
import numpy as np
a=np.random.randn(10,10)
print(a.min(), a.max())

-3.6387109098200314 3.066133351404942


In [ ]:
#연습문제2-3
a=np.arange(0,9).reshape(3,3)
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
#연습문제2-4
arr=np.arange(1,25)
y=np.resize(arr,(4,6))
y

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [ ]:
#연습문제2-5
print(y[1:3,1:5])

[[ 8  9 10 11]
 [14 15 16 17]]


In [ ]:
#연습문제2-6
print(y[2:,::-1])

[[18 17 16 15 14 13]
 [24 23 22 21 20 19]]


In [ ]:
#연습문제2-7
print(arr[1::2])

[ 2  4  6  8 10 12 14 16 18 20 22 24]


In [ ]:
#연습문제2-8
print(arr[9:20])

[10 11 12 13 14 15 16 17 18 19 20]


In [ ]:
#연습문제3
arr=np.arange(1,21)
print('마지막 원소:',arr[-1])
print('모든 원소의 합:',arr.sum())
print('모든 원소의 평균:',arr.min())
new_arr=np.random.randint(1,21)
print(new_arr)

마지막 원소: 20
모든 원소의 합: 210
모든 원소의 평균: 1
6


In [3]:
#연습문제4
import numpy as np
salary=[200,150,180,220,250]
new_salary=np.array(salary,dtype='float64')*1.5
print('인상된 금액:', new_salary)
avg_salary=new_salary.mean()
print('평균 금액:', avg_salary)
result=(new_salary>=avg_salary)
print('평균이상인 원소: ',new_salary[result])
print('평균이상인 원소의 개수: ',new_salary[result].size )

인상된 금액: [300. 225. 270. 330. 375.]
평균 금액: 300.0
평균이상인 원소:  [300. 330. 375.]
평균이상인 원소의 개수:  3
