<a href="https://colab.research.google.com/github/8WHOVIAN8/DAstudy/blob/%EC%8B%A0%EC%84%B1%ED%98%84/week1_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**실습 코드**

In [ ]:
import numpy as np #넘파이 추가

2.1) 리스트로 배열 생성

In [ ]:
arr1=np.array(range(1,6))
print('일차원:',arr1)
arr2=np.array([[1,2,3],[4,5,6]])
print('이차원:',arr2)
arr3=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print('삼차원:',arr3)

일차원: [1 2 3 4 5]
이차원: [[1 2 3]
 [4 5 6]]
삼차원: [[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


2.2) 배열 생성 및 초기화

In [ ]:
a=np.zeros(10)
print(a)
b=np.ones((2,3))
print(b)
c=np.full((2,2),1.5)
print(c)
d=np.eye(3)
print(d)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[1. 1. 1.]
 [1. 1. 1.]]
[[1.5 1.5]
 [1.5 1.5]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


2.3) 생성한 값으로 배열 생성

In [ ]:
a=np.arange(1,21)
print(a)
b=np.linspace(0,10,5)
print(b)
c=np.logspace(np.log10(10),np.log10(100),5)
print(c)
d=np.logspace(1,2,5)
print(d)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[ 0.   2.5  5.   7.5 10. ]
[ 10.          17.7827941   31.6227766   56.23413252 100.        ]
[ 10.          17.7827941   31.6227766   56.23413252 100.        ]


2.4) 난수 기반으로 배열 생성

In [ ]:
print(np.random.random((4,3))) #random 함수- [0,1)사이의 랜덤값
print(np.random.randint(1,10,(3,3)))#randint 함수- 정한 범위내의 랜덤int값 반환
print(np.random.rand(3,3))#rand- [0,1)의 균등분포 반환
print(np.random.randn(3,3))#randn- 표준 정규 분포에서 표본추출

[[0.93723658 0.30911575 0.967568  ]
 [0.60899655 0.22034601 0.22072368]
 [0.6967241  0.42334021 0.90057888]
 [0.08960528 0.53083037 0.95995616]]
[[4 4 3]
 [8 5 3]
 [2 1 3]]
[[4.71844784e-01 4.19503494e-01 5.54901763e-01]
 [2.18820392e-04 7.83565552e-01 5.23235302e-01]
 [1.84352433e-01 1.52379145e-01 2.19003405e-01]]
[[ 1.37075576  0.01646608 -0.04100061]
 [ 1.44860125 -0.38141915  0.80509325]
 [ 1.07327852  1.3038606  -0.7254614 ]]


3.2) 넘파이 배열 속성 정보

In [ ]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr)
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)
print(arr.itemsize)
print(arr.data)

[[1 2 3]
 [4 5 6]]
2
(2, 3)
6
int64
8


3.3) 배열의 인덱싱

In [ ]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr)
print(arr[0,2])#이차원 배열의 인덱싱
arr[0,2]=10
print(arr)

[[1 2 3]
 [4 5 6]]
3
[[ 1  2 10]
 [ 4  5  6]]


3.4) 배열의 슬라이싱

In [ ]:
a1=np.arange(1,10)#1차원
print(a1[2:9])
print(a1[::5])
a2=np.arange(1,10).reshape(3,3)#2차원
print(a2[2:,::-1])

[3 4 5 6 7 8 9]
[1 6]
[[9 8 7]]


3.5) 논리 인덱싱

In [ ]:
a=np.arange(1,5)
b=[True,True,False,False]
print(a[b])
b=np.arange(10)
print(b[b<5])
print(b[~(b==8)])
print(b[b%3==0])
print(b[(b%2==0)&(b>3)])

[1 2]
[0 1 2 3 4]
[0 1 2 3 4 5 6 7 9]
[0 3 6 9]
[4 6 8]


4.1) 배열의 연산

In [ ]:
print(np.add(1,2))
print(np.subtract(1,2))
print(np.multiply(1,2))
print(np.divide(1,2))
print(np.mod(1,2))

3
-1
2
0.5
1


In [ ]:
a=np.arange(1,10).reshape(3,3)
print(a.sum())
print(np.sum(a,axis=0))
print(a.max(axis=1))
print(a.mean(axis=0))
#표준편차 .std()/np.std()가능

45
[12 15 18]
[3 6 9]
[4. 5. 6.]


4.2) 브로드캐스팅 연산

In [ ]:
#shape가 다를때
a=np.arange(5).reshape(1,5)
print(a+100)
b=np.arange(5).reshape(5,1)
print(a+b)

[[100 101 102 103 104]]
[[0 1 2 3 4]
 [1 2 3 4 5]
 [2 3 4 5 6]
 [3 4 5 6 7]
 [4 5 6 7 8]]


4.3) 넘파이 벡터 연산

In [ ]:
result=np.sum(a+b)
print(result)

100


5.1) 전치

In [ ]:
a=np.random.randint(1,10,(3,3))
print(a)
print(a.T)

[[7 4 2]
 [9 8 4]
 [6 8 7]]
[[7 9 6]
 [4 8 8]
 [2 4 7]]


5.2) 배열 형태 변경

In [ ]:
a=np.arange(1,7).reshape(3,2)
print(a)
b=a.ravel()
b[0]=100
print(b)
print(a)#원본 배열도 수정된다.
#reshape애서도 동일한 메모리를 공유하므로 배열들의 데이터가 같이 수정된다.

[[1 2]
 [3 4]
 [5 6]]
[100   2   3   4   5   6]
[[100   2]
 [  3   4]
 [  5   6]]


5.3) 배열 요소 추가 및 삭제

In [ ]:
x=np.arange(20).reshape(4,5)
print(x)
y=np.resize(x,(1,5))#resize- 동일한 메모리를 공유하지 않는다.
print(y)
a=np.append(x,y,axis=0)#append
print(a)
b=np.delete(a,0,axis=0)#delete
print(b)
k=np.insert(b,0,100,axis=0)#insert
print(k)#모두 축 지정을 안하면 1차원으로 변환된다.

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[0 1 2 3 4]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [ 0  1  2  3  4]]
[[ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [ 0  1  2  3  4]]
[[100 100 100 100 100]
 [  5   6   7   8   9]
 [ 10  11  12  13  14]
 [ 15  16  17  18  19]
 [  0   1   2   3   4]]


5.4) 배열 결합

In [ ]:
a1=np.array([[1,2,3]])
a2=np.array([[4,5,6]])
arr1=np.concatenate((a1,a2))#concatenate
print(arr1)
arr2=np.concatenate((a1,a2),axis=1)
print(arr2)
arr3=np.vstack((a1,a2))#vstack- axis=0 방향
print(arr3)
arr4=np.hstack((a1,a2))#hstack- axis=1 방향
print(arr4)
print(np.vsplit(arr3,2))#vsplit
arr1=np.insert(arr1,0,0,axis=1)
print(arr1)
print(np.hsplit(arr1,2))#hsplit

[[1 2 3]
 [4 5 6]]
[[1 2 3 4 5 6]]
[[1 2 3]
 [4 5 6]]
[[1 2 3 4 5 6]]
[array([[1, 2, 3]]), array([[4, 5, 6]])]
[[0 1 2 3]
 [0 4 5 6]]
[array([[0, 1],
       [0, 4]]), array([[2, 3],
       [5, 6]])]


**연습 문제 코드**

연습1

In [ ]:
arr=np.arange(1,11)
print(arr)
print('ndim:',arr.ndim)
print(arr.shape)
print(arr.dtype)
print('size:',arr.size)

[ 1  2  3  4  5  6  7  8  9 10]
ndim: 1
(10,)
int64
size: 10


연습2

In [ ]:
#1
arr1=np.arange(10,51)
print(arr1[::-1])
#2
arr2=np.random.random((10,10))
print(arr2.min(),end=' ')
print(arr2.max())
#3
arr3=np.arange(9).reshape(3,3)
print(arr3)
#4
arr4=np.arange(1,25).reshape(4,6)
print(arr4)
#5
print(arr4[1:3,1:5])
#6
print(arr4[2:,::-1])
#7
print(arr4[arr4%2==0])
#8
print(arr4[(arr4>=10)&(arr4<=20)])

[50 49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27
 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]
0.011678096593641718 0.9943249568763706
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]
[[ 8  9 10 11]
 [14 15 16 17]]
[[18 17 16 15 14 13]
 [24 23 22 21 20 19]]
[ 2  4  6  8 10 12 14 16 18 20 22 24]
[10 11 12 13 14 15 16 17 18 19 20]


array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

연습3

In [ ]:
arr=np.arange(1,21)
print('마지막 원소:',arr[-1])
print('모든 원소의 합:',arr.sum())
avg=arr.sum()//arr.size
print('모든 원소의 평균:',avg)

마지막 원소: 20
모든 원소의 합: 210
모든 원소의 평균: 10


연습4

In [ ]:
salary=[200,100,150,180,220,250]
new_salary=np.array(salary,dtype='float64')*1.5
print('인상된 금액:',new_salary)
avg_salary=new_salary.sum()//new_salary.size
print('평균 금액:',avg_salary)
result=np.array(new_salary>avg_salary)
print('평균 이상인 원소:', new_salary[result])
print('평균 이상인 원소의 개수:',np.sum(result))

인상된 금액: [300. 150. 225. 270. 330. 375.]
평균 금액: 275.0
평균 이상인 원소: [300. 330. 375.]
평균 이상인 원소의 개수: 3
